function dct_retrieval(inputImagePath, outputWatermarkPath, jsonInputFilePath)

%============================== CHANGED ==============================
%The original retrieval code expected one header and one watermark copy.
%The new embedding code stores six complete regional copies, so retrieval
%must read the regional layout and exact block locations from the JSON file.
if exist(jsonInputFilePath, 'file') ~= 2
    error('JSON metadata file does not exist: %s', jsonInputFilePath);
end

jsonMetadata = jsondecode(fileread(jsonInputFilePath));

requiredFields = {
    'originalHeight'
    'originalWidth'
    'paddedHeight'
    'paddedWidth'
    'watermarkHeight'
    'watermarkWidth'
    'numEmbeddedBits'
    'blockSize'
    'coeff1'
    'coeff2'
    'metadataLength'
    'payloadLength'
    'numCopies'
    'regionalBlockIndices'
};

%Check that the JSON was generated by the new regional-copy embedder.
for fieldIndex = 1:length(requiredFields)

    fieldName = requiredFields{fieldIndex};

    if ~isfield(jsonMetadata, fieldName)
        error(['JSON metadata is missing field "%s". Regenerate the ' ...
               'watermarked image using the regional-copy dct_embed.m.'], ...
               fieldName);
    end
end

originalH = double(jsonMetadata.originalHeight);
originalW = double(jsonMetadata.originalWidth);
paddedH = double(jsonMetadata.paddedHeight);
paddedW = double(jsonMetadata.paddedWidth);

wmH = double(jsonMetadata.watermarkHeight);
wmW = double(jsonMetadata.watermarkWidth);
numBits = double(jsonMetadata.numEmbeddedBits);

blockSize = double(jsonMetadata.blockSize);
coeff1 = double(jsonMetadata.coeff1(:).');
coeff2 = double(jsonMetadata.coeff2(:).');

metadataLength = double(jsonMetadata.metadataLength);
payloadLength = double(jsonMetadata.payloadLength);
numCopies = double(jsonMetadata.numCopies);

%Validate watermark dimensions and payload size.
if wmH < 1 || wmW < 1 || numBits ~= wmH * wmW
    error('JSON watermark metadata is invalid.');
end

if payloadLength ~= metadataLength + numBits
    error('JSON payloadLength is inconsistent.');
end

if mod(paddedH, blockSize) ~= 0 || ...
        mod(paddedW, blockSize) ~= 0
    error('Padded dimensions are not divisible by blockSize.');
end

%The JSON stores all regional block indices in copy-major order.
flatCopyBlockIndices = ...
    double(jsonMetadata.regionalBlockIndices(:).');

expectedIndexCount = numCopies * payloadLength;

if length(flatCopyBlockIndices) ~= expectedIndexCount
    error(['JSON contains %d regional block indices, but %d are ' ...
           'required.'], ...
           length(flatCopyBlockIndices), expectedIndexCount);
end

%Convert the flattened list back into:
%rows = regional copies
%columns = header/watermark payload positions
copyBlockIndices = reshape( ...
    flatCopyBlockIndices, [payloadLength, numCopies]).';
%============================ END CHANGE =============================

%Read attacked/watermarked image
img = imread(inputImagePath);

if size(img, 3) ~= 3
    error('Input image must be an RGB image.');
end

[imgH, imgW, ~] = size(img);

%============================== CHANGED ==============================
%All evaluation attacks are expected to be saved at the original image size.
%The crop attack is resized back to this size before retrieval.
if imgH ~= originalH || imgW ~= originalW
    error(['Input image is %d x %d, but metadata expects %d x %d. ' ...
           'The attacked image must be resized back to the original size.'], ...
           imgH, imgW, originalH, originalW);
end

%Detect the project's known center-80-percent crop followed by
%nearest-neighbour resizing.
lowerInputPath = lower(inputImagePath);

isCropResizeAttack = ...
    ~isempty(strfind(lowerInputPath, 'crop80_resize'));

if isCropResizeAttack

    if isfield(jsonMetadata, 'supportedCropRatio')
        cropRatio = double(jsonMetadata.supportedCropRatio);
    else
        cropRatio = 0.80;
    end

    %Reverse the known resize and place the retained crop back at its
    %original center coordinates.
    [registeredImg, validMask] = undo_center_crop_resize( ...
        img, originalH, originalW, cropRatio);

    fprintf(['Detected crop80_resize. Reversed the known nearest-neighbour ' ...
             'resize and restored the retained center coordinates.\n']);
else
    registeredImg = img;

    %For attacks that do not remove image regions, every pixel is valid.
    validMask = true(originalH, originalW);
end
%============================ END CHANGE =============================

% Convert RGB image to Y brightness channel
%CHANGED: use registeredImg instead of img so the known crop/resize attack
%is returned to the original coordinate system before DCT extraction.
imgDouble = double(registeredImg);

Y = 0.299 * imgDouble(:, :, 1) + ...
    0.587 * imgDouble(:, :, 2) + ...
    0.114 * imgDouble(:, :, 3);

%============================== CHANGED ==============================
%Use the exact padded dimensions stored by embedding instead of calculating
%them only from the attacked image.
calculatedPadH = paddedH - originalH;
calculatedPadW = paddedW - originalW;

if calculatedPadH < 0 || calculatedPadW < 0
    error('JSON padded dimensions are invalid.');
end
%============================ END CHANGE =============================

% Rebuild padded Y channel
paddedY = zeros(paddedH, paddedW);
paddedY(1:originalH, 1:originalW) = Y;

%============================== CHANGED ==============================
%Rebuild a matching validity mask. A false pixel represents image content
%that was physically removed by cropping.
paddedValid = false(paddedH, paddedW);
paddedValid(1:originalH, 1:originalW) = validMask;
%============================ END CHANGE =============================

if calculatedPadH > 0
    paddedY(originalH+1:paddedH, 1:originalW) = ...
        repmat(Y(end, :), calculatedPadH, 1);

    %============================ CHANGED ============================
    paddedValid(originalH+1:paddedH, 1:originalW) = ...
        repmat(validMask(end, :), calculatedPadH, 1);
    %========================== END CHANGE ===========================
end

if calculatedPadW > 0
    paddedY(:, originalW+1:paddedW) = ...
        repmat(paddedY(:, originalW), 1, calculatedPadW);

    %============================ CHANGED ============================
    paddedValid(:, originalW+1:paddedW) = ...
        repmat(paddedValid(:, originalW), 1, calculatedPadW);
    %========================== END CHANGE ===========================
end

% Calculate block grid
numBlocksH = paddedH / blockSize;
numBlocksW = paddedW / blockSize;
maxBits = numBlocksH * numBlocksW;

if any(copyBlockIndices(:) < 1) || ...
        any(copyBlockIndices(:) > maxBits)
    error('One or more regional block indices are outside the image.');
end

D = create_dct_matrix(blockSize);

%============================== CHANGED ==============================
%The original code extracted one binary result from one block per bit.
%The new code extracts the signed coefficient difference c1-c2 from all six
%regional copies.
%
%Rows = payload positions
%Columns = regional copies
%NaN = this block was removed or partly removed by the crop
payloadMargins = nan(payloadLength, numCopies);

for copyIndex = 1:numCopies

    for payloadIndex = 1:payloadLength

        blockIndex = copyBlockIndices(copyIndex, payloadIndex);

        blockRow = floor((blockIndex - 1) / numBlocksW) + 1;
        blockCol = mod(blockIndex - 1, numBlocksW) + 1;

        rowStart = (blockRow - 1) * blockSize + 1;
        colStart = (blockCol - 1) * blockSize + 1;

        %Check whether the complete original 8x8 block survived cropping.
        blockValid = paddedValid( ...
            rowStart:rowStart+blockSize-1, ...
            colStart:colStart+blockSize-1);

        %Partially cropped blocks are not trustworthy and are ignored.
        if ~all(blockValid(:))
            continue;
        end

        block = paddedY(rowStart:rowStart+blockSize-1, ...
                        colStart:colStart+blockSize-1);

        dctBlock = D * block * D';

        c1 = dctBlock(coeff1(1), coeff1(2));
        c2 = dctBlock(coeff2(1), coeff2(2));

        %Positive margin means bit 1.
        %Negative margin means bit 0.
        payloadMargins(payloadIndex, copyIndex) = c1 - c2;
    end
end
%============================ END CHANGE =============================

%============================== CHANGED ==============================
%Check each repeated 80-bit header for diagnostics.
%This reports which regional copies survived each attack.
storedPadH = calculatedPadH;
storedPadW = calculatedPadW;

expectedMetadataBits = build_metadata_bits( ...
    wmH, wmW, numBits, storedPadH, storedPadW);

headerScores = nan(numCopies, 1);
survivingHeaderBits = zeros(numCopies, 1);

for copyIndex = 1:numCopies

    headerMargins = payloadMargins(1:metadataLength, copyIndex);

    validHeader = ~isnan(headerMargins);
    survivingHeaderBits(copyIndex) = sum(validHeader);

    if any(validHeader)

        extractedHeader = headerMargins(validHeader) > 0;

        headerScores(copyIndex) = mean( ...
            extractedHeader == expectedMetadataBits(validHeader));
    end
end
%============================ END CHANGE =============================

%============================== CHANGED ==============================
%Combine all surviving watermark copies using clipped soft voting.
%This is more reliable than trusting one binary c1>c2 decision.
watermarkMargins = payloadMargins(metadataLength+1:end, :);

watermarkBits = false(numBits, 1);
survivingCopiesPerBit = zeros(numBits, 1);

if isfield(jsonMetadata, 'strength')
    strength = double(jsonMetadata.strength);
else
    strength = 20;
end

%Prevent one abnormal coefficient value from overpowering all other copies.
clipLimit = max(1, 2 * strength);

for bitIndex = 1:numBits

    bitMargins = watermarkMargins(bitIndex, :);

    %Remove regional copies whose corresponding block was cropped away.
    bitMargins = bitMargins(~isnan(bitMargins));

    survivingCopiesPerBit(bitIndex) = length(bitMargins);

    if isempty(bitMargins)
        %No copy of this bit survived.
        watermarkBits(bitIndex) = false;
        continue;
    end

    %Limit unusually large margins before combining the copies.
    clippedMargins = min(max( ...
        bitMargins, -clipLimit), clipLimit);

    %A positive combined margin means the final bit is 1.
    watermarkBits(bitIndex) = sum(clippedMargins) > 0;
end

missingBitCount = sum(survivingCopiesPerBit == 0);
%============================ END CHANGE =============================

%% Reconstruct and save watermark

reconstructedWatermark = reshape( ...
    logical(watermarkBits), [wmH, wmW]);

imwrite(uint8(reconstructedWatermark) * 255, ...
    outputWatermarkPath);

%============================== CHANGED ==============================
%The status output now reports regional-copy survival and header agreement.
fprintf('DCT regional-copy retrieval complete.\n');
fprintf('Recovered watermark: %d x %d (%d bits).\n', ...
    wmW, wmH, numBits);
fprintf('Stored padding: %d row(s), %d column(s).\n', ...
    storedPadH, storedPadW);
fprintf('Metadata source: JSON file.\n');
fprintf('Regional copies configured: %d.\n', numCopies);
fprintf('Average surviving copies per watermark bit: %.2f.\n', ...
    mean(survivingCopiesPerBit));
fprintf('Minimum surviving copies for any watermark bit: %d.\n', ...
    min(survivingCopiesPerBit));
fprintf('Watermark bits with no surviving copy: %d.\n', ...
    missingBitCount);

for copyIndex = 1:numCopies

    if isnan(headerScores(copyIndex))
        fprintf('Copy %d header: no surviving header blocks.\n', ...
            copyIndex);
    else
        fprintf(['Copy %d header agreement: %.2f%% ' ...
                 '(%d surviving header bits).\n'], ...
                 copyIndex, ...
                 100 * headerScores(copyIndex), ...
                 survivingHeaderBits(copyIndex));
    end
end

if missingBitCount > 0
    warning(['%d watermark bits had no surviving regional copy and were ' ...
             'set to zero.'], missingBitCount);
end
%============================ END CHANGE =============================

end

%============================== CHANGED ==============================
function bits = build_metadata_bits(wmH, wmW, numBits, padH, padW)
%Rebuild the known 80-bit header so every regional header can be checked.

hBits = dec2bin(uint16(wmH), 16) - '0';
wBits = dec2bin(uint16(wmW), 16) - '0';
nBits = dec2bin(uint32(numBits), 32) - '0';
padHBits = dec2bin(uint8(padH), 8) - '0';
padWBits = dec2bin(uint8(padW), 8) - '0';

bits = logical([hBits(:); wBits(:); nBits(:); ...
                padHBits(:); padWBits(:)]);

end

function [registeredImg, validMask] = undo_center_crop_resize( ...
    attackedImg, originalH, originalW, cropRatio)
%Reverse the known project attack:
%1. The image was center-cropped to cropRatio.
%2. The cropped image was resized back to the original dimensions.
%
%This function shrinks it back to the crop dimensions and places the
%retained content at its original center coordinates.

cropH = round(originalH * cropRatio);
cropW = round(originalW * cropRatio);

rowStart = floor((originalH - cropH) / 2) + 1;
colStart = floor((originalW - cropW) / 2) + 1;

recoveredCrop = nearest_resize_manual( ...
    attackedImg, cropH, cropW);

registeredImg = zeros(originalH, originalW, 3, 'uint8');

registeredImg( ...
    rowStart:rowStart+cropH-1, ...
    colStart:colStart+cropW-1, :) = recoveredCrop;

%Only the restored center region contains surviving image information.
validMask = false(originalH, originalW);

validMask( ...
    rowStart:rowStart+cropH-1, ...
    colStart:colStart+cropW-1) = true;

end

function out = nearest_resize_manual(img, newH, newW)
%Use the same deterministic nearest-neighbour mapping as the attack code.

[oldH, oldW, channels] = size(img);
out = zeros(newH, newW, channels, 'uint8');

for r = 1:newH

    oldR = round((r - 0.5) * oldH / newH + 0.5);
    oldR = min(max(oldR, 1), oldH);

    for c = 1:newW

        oldC = round((c - 0.5) * oldW / newW + 0.5);
        oldC = min(max(oldC, 1), oldW);

        out(r, c, :) = img(oldR, oldC, :);
    end
end

end
%============================ END CHANGE =============================

function D = create_dct_matrix(N)

D = zeros(N, N);

for k = 0:N-1
    for n = 0:N-1
        if k == 0
            alpha = sqrt(1 / N);
        else
            alpha = sqrt(2 / N);
        end

        D(k+1, n+1) = alpha * ...
            cos(((2*n + 1) * k * pi) / (2 * N));
    end
end

end
